from datetime import timedelta
import uuid

from lib.db import db, pwd_context
from routers.common import now


CREATE_ORDER = [
    "users",
    "customers",
    "products",
    "sales_targets",
    "opportunities",
    "activities",
    "quotations",
    "purchase_orders",
    "tasks",
]

CLEAR_ORDER = [
    "tasks",
    "purchase_orders",
    "quotations",
    "activities",
    "opportunities",
    "sales_targets",
    "customers",
    "products",
    "users",
]


def _id() -> str:
    return str(uuid.uuid4())


def _date(days: int = 0) -> str:
    return (now() + timedelta(days=days)).date().isoformat()


def _demo_doc(**fields):
    return {"id": _id(), "is_demo": True, "created_at": now(), **fields}


async def _demo_exists() -> bool:
    for collection in CREATE_ORDER:
        if await db[collection].find_one({"is_demo": True}, {"_id": 1}):
            return True
    return False


async def _rollback(created: dict[str, list[str]]) -> None:
    for collection in reversed(CREATE_ORDER):
        ids = created.get(collection, [])
        if ids:
            await db[collection].delete_many({"id": {"$in": ids}})


async def generate_demo_data() -> dict:
    if await _demo_exists():
        raise ValueError("Demo data sudah tersedia. Jalankan Clear Dummy terlebih dahulu.")

    created = {name: [] for name in CREATE_ORDER}
    try:
        manager = _demo_doc(
            user_id="USR-DEMO-001", name="Demo Manager", email="demo.manager@crm-demo.local",
            role="SALES_MANAGER", manager_id=None, phone="08120000001", status="Active",
            password_hash=pwd_context.hash("Password123"), failed_login_attempts=0, locked_until=None,
        )
        users = [manager]
        for index in range(2, 11):
            users.append(_demo_doc(
                user_id=f"USR-DEMO-{index:03d}", name=f"Demo Sales {index - 1}",
                email=f"demo.sales{index - 1:02d}@crm-demo.local", role="SALES",
                manager_id=manager["id"], phone=f"08120000{index:03d}", status="Active",
                password_hash=pwd_context.hash("Password123"), failed_login_attempts=0, locked_until=None,
            ))
        await db.users.insert_many(users)
        created["users"] = [x["id"] for x in users]
        sales_users = users[1:]

        customers = []
        for index in range(1, 11):
            sales = sales_users[(index - 1) % len(sales_users)]
            customers.append(_demo_doc(
                customer_id=f"CUS-DEMO-{index:03d}", name=f"Demo Customer {index:02d}",
                company_name=f"PT Demo Industri {index:02d}", company=f"PT Demo Industri {index:02d}",
                industry=["Manufacturing", "Oil & Gas", "Automation", "Food & Beverage"][index % 4],
                source="Dummy Data", city="Jakarta", province="DKI Jakarta", phone=f"021555{index:04d}",
                email=f"customer{index:02d}@crm-demo.local", pic_name=f"PIC Demo {index:02d}",
                pic_position="Procurement", status="Active", sales_id=sales["id"], sales_name=sales["name"],
                address=f"Jl. Demo Industri No. {index}, Jakarta", notes="Generated by CRM Generate Dummy.", updated_at=now(),
            ))
        await db.customers.insert_many(customers)
        created["customers"] = [x["id"] for x in customers]

        products = []
        for index in range(1, 11):
            products.append(_demo_doc(
                code=f"PRD-DEMO-{index:03d}", name=f"Demo Product {index:02d}",
                brand=["Axiomtek", "Watlow", "ICPDAS", "Eurotherm"][index % 4],
                category=["Industrial PC", "Heater", "Remote I/O", "Controller"][index % 4], unit="pcs",
                default_price=float(index * 2500000), supplier="Demo Supplier", status="Active",
                description="Generated by CRM Generate Dummy.", updated_at=now(),
            ))
        await db.products.insert_many(products)
        created["products"] = [x["id"] for x in products]

        targets = []
        for index, sales in enumerate(sales_users, start=1):
            targets.append(_demo_doc(
                sales_id=sales["id"], sales_name=sales["name"], year=now().year,
                target=float(300000000 + index * 25000000), updated_at=now(),
            ))
        await db.sales_targets.insert_many(targets)
        created["sales_targets"] = [x["id"] for x in targets]

        stages = ["Lead", "Qualification", "Proposal", "Negotiation", "Won", "Lost"]
        opportunities = []
        for index in range(1, 11):
            customer = customers[index - 1]
            sales = sales_users[(index - 1) % len(sales_users)]
            stage = stages[(index - 1) % len(stages)]
            opportunities.append(_demo_doc(
                opportunity_id=f"OPP-DEMO-{index:03d}", name=f"Demo Opportunity {index:02d}",
                customer_id=customer["id"], customer_name=customer["name"], sales_id=sales["id"], sales_name=sales["name"],
                value=float(50000000 + index * 17500000),
                probability={"Lead": 10, "Qualification": 25, "Proposal": 50, "Negotiation": 75, "Won": 100, "Lost": 0}[stage],
                stage=stage, target_close=_date(15 + index * 3),
                brand=["Axiomtek", "Watlow", "ICPDAS", "Eurotherm"][index % 4],
                product=products[(index - 1) % len(products)]["name"], next_action="Follow up customer",
                description="Generated by CRM Generate Dummy.", loss_reason="Budget / competition" if stage == "Lost" else None,
                updated_at=now(),
            ))
        await db.opportunities.insert_many(opportunities)
        created["opportunities"] = [x["id"] for x in opportunities]

        activity_types = ["Call", "WhatsApp", "Email", "Meeting", "Visit", "Presentation", "Follow Up"]
        activities = []
        for index in range(1, 11):
            customer = customers[index - 1]
            opportunity = opportunities[index - 1]
            sales = sales_users[(index - 1) % len(sales_users)]
            activities.append(_demo_doc(
                activity_id=f"ACT-DEMO-{index:03d}", subject=f"Demo Activity {index:02d}",
                activity_type=activity_types[(index - 1) % len(activity_types)], date=_date(-index),
                customer_id=customer["id"], customer_name=customer["name"], opportunity_id=opportunity["id"],
                sales_id=sales["id"], sales_name=sales["name"],
                next_follow_up=_date(-2) if index in {3, 7} else _date(index),
                status="Completed" if index in {1, 4, 8} else "Open", description="Generated by CRM Generate Dummy.", updated_at=now(),
            ))
        await db.activities.insert_many(activities)
        created["activities"] = [x["id"] for x in activities]

        quotation_statuses = ["Draft", "Sent", "Negotiation", "Approved", "Rejected", "Expired", "Converted"]
        quotations = []
        for index in range(1, 11):
            customer = customers[index - 1]
            opportunity = opportunities[index - 1]
            sales = sales_users[(index - 1) % len(sales_users)]
            product = products[(index - 1) % len(products)]
            unit_price = float(product["default_price"])
            quantity = (index % 3) + 1
            subtotal = unit_price * quantity
            discount_total = subtotal * (0.05 if index % 4 == 0 else 0)
            tax_total = (subtotal - discount_total) * 0.11
            quotations.append(_demo_doc(
                number=f"QT-DEMO-{index:03d}", customer_id=customer["id"], customer_name=customer["name"],
                sales_id=sales["id"], sales_name=sales["name"], opportunity_id=opportunity["id"],
                date=_date(-index), valid_until=_date(30), payment_term="30 Days", delivery_term="4-6 Weeks",
                notes="Generated by CRM Generate Dummy.",
                items=[{"product_id": product["id"], "description": product["name"], "quantity": quantity,
                        "unit_price": unit_price, "discount": discount_total, "tax": tax_total,
                        "total": subtotal - discount_total + tax_total}],
                subtotal=subtotal, discount_total=discount_total, tax_total=tax_total,
                grand_total=subtotal - discount_total + tax_total,
                status=quotation_statuses[(index - 1) % len(quotation_statuses)], updated_at=now(),
            ))
        await db.quotations.insert_many(quotations)
        created["quotations"] = [x["id"] for x in quotations]

        order_statuses = ["Received", "Waiting Order", "Confirmed", "Processing", "Indent", "Ready Stock", "Delivery", "Completed", "Cancelled"]
        purchase_orders = []
        for index in range(1, 11):
            customer = customers[index - 1]
            quotation = quotations[index - 1]
            sales = sales_users[(index - 1) % len(sales_users)]
            product = products[(index - 1) % len(products)]
            quantity = (index % 3) + 1
            unit_price = float(product["default_price"])
            purchase_orders.append(_demo_doc(
                po_number=f"PO-DEMO-{index:03d}", customer_id=customer["id"], customer_name=customer["name"],
                sales_id=sales["id"], sales_name=sales["name"], date=_date(-index),
                status=order_statuses[(index - 1) % len(order_statuses)], quotation_number=quotation["number"], quotation_manual=False,
                items=[{"product_id": product["id"], "description": product["name"], "quantity": quantity,
                        "unit_price": unit_price, "discount": 0, "tax": 11}],
                total=unit_price * quantity * 1.11, eta=_date(7 + index), payment_term="30 Days",
                supplier="Demo Supplier", shipping_address=customer["address"], document_name=f"PO-DEMO-{index:03d}.pdf", updated_at=now(),
            ))
        await db.purchase_orders.insert_many(purchase_orders)
        created["purchase_orders"] = [x["id"] for x in purchase_orders]

        tasks = []
        for index in range(1, 11):
            customer = customers[index - 1]
            opportunity = opportunities[index - 1]
            sales = sales_users[(index - 1) % len(sales_users)]
            tasks.append(_demo_doc(
                title=f"Demo Task {index:02d}", due_date=_date(index - 5),
                priority=["Low", "Medium", "High"][index % 3], status="Completed" if index in {2, 6, 10} else "Pending",
                customer_name=customer["name"], opportunity_name=opportunity["name"], assigned_user=sales["name"], updated_at=now(),
            ))
        await db.tasks.insert_many(tasks)
        created["tasks"] = [x["id"] for x in tasks]

        # Keep the same relational contract as production records.
        user_ids = {x["id"] for x in users}
        customer_ids = {x["id"] for x in customers}
        product_ids = {x["id"] for x in products}
        opportunity_ids = {x["id"] for x in opportunities}
        quotation_numbers = {x["number"] for x in quotations}
        assert all(x.get("manager_id") in user_ids or x.get("manager_id") is None for x in users)
        assert all(x.get("sales_id") in user_ids for x in customers)
        assert all(x.get("customer_id") in customer_ids and x.get("sales_id") in user_ids for x in opportunities)
        assert all(x.get("customer_id") in customer_ids and x.get("opportunity_id") in opportunity_ids and x.get("sales_id") in user_ids for x in activities)
        assert all(x.get("customer_id") in customer_ids and x.get("sales_id") in user_ids and x.get("opportunity_id") in opportunity_ids and all(i.get("product_id") in product_ids for i in x.get("items", [])) for x in quotations)
        assert all(x.get("customer_id") in customer_ids and x.get("sales_id") in user_ids and x.get("quotation_number") in quotation_numbers and all(i.get("product_id") in product_ids for i in x.get("items", [])) for x in purchase_orders)

        return {"counts": {name: len(ids) for name, ids in created.items()}}
    except Exception:
        await _rollback(created)
        raise


async def _find_production_reference(collection: str, query: dict) -> bool:
    return await db[collection].find_one({"is_demo": {"$ne": True}, **query}, {"_id": 1}) is not None


async def clear_demo_data() -> dict:
    demo_users = await db.users.find({"is_demo": True}, {"id": 1, "user_id": 1, "name": 1}).to_list(1000)
    demo_customers = await db.customers.find({"is_demo": True}, {"id": 1, "customer_id": 1, "name": 1}).to_list(1000)
    demo_products = await db.products.find({"is_demo": True}, {"id": 1, "code": 1}).to_list(1000)
    demo_opportunities = await db.opportunities.find({"is_demo": True}, {"id": 1, "opportunity_id": 1, "name": 1}).to_list(1000)
    demo_quotations = await db.quotations.find({"is_demo": True}, {"id": 1, "number": 1}).to_list(1000)

    demo_any = any([
        bool(demo_users), bool(demo_customers), bool(demo_products), bool(demo_opportunities), bool(demo_quotations),
        await db.tasks.find_one({"is_demo": True}, {"_id": 1}),
        await db.purchase_orders.find_one({"is_demo": True}, {"_id": 1}),
        await db.quotations.find_one({"is_demo": True}, {"_id": 1}),
        await db.activities.find_one({"is_demo": True}, {"_id": 1}),
        await db.opportunities.find_one({"is_demo": True}, {"_id": 1}),
        await db.sales_targets.find_one({"is_demo": True}, {"_id": 1}),
    ])
    if not demo_any:
        return {"deleted": {name: 0 for name in CLEAR_ORDER}}

    user_ids = [x["id"] for x in demo_users]
    user_names = [x.get("name") for x in demo_users if x.get("name")]
    customer_ids = [x["id"] for x in demo_customers]
    customer_names = [x.get("name") for x in demo_customers if x.get("name")]
    product_ids = [x["id"] for x in demo_products]
    opportunity_ids = [x["id"] for x in demo_opportunities]
    opportunity_names = [x.get("name") for x in demo_opportunities if x.get("name")]
    quotation_numbers = [x["number"] for x in demo_quotations if x.get("number")]

    reference_checks = [
        ("customers", {"$or": [{"sales_id": {"$in": user_ids}}, {"sales_name": {"$in": user_names}}]}),
        ("opportunities", {"$or": [{"sales_id": {"$in": user_ids}}, {"sales_name": {"$in": user_names}}, {"customer_id": {"$in": customer_ids}}, {"customer_name": {"$in": customer_names}}]}),
        ("activities", {"$or": [{"sales_id": {"$in": user_ids}}, {"sales_name": {"$in": user_names}}, {"customer_id": {"$in": customer_ids}}, {"customer_name": {"$in": customer_names}}, {"opportunity_id": {"$in": opportunity_ids}}]}),
        ("quotations", {"$or": [{"sales_id": {"$in": user_ids}}, {"sales_name": {"$in": user_names}}, {"customer_id": {"$in": customer_ids}}, {"customer_name": {"$in": customer_names}}, {"opportunity_id": {"$in": opportunity_ids}}]}),
        ("purchase_orders", {"$or": [{"sales_id": {"$in": user_ids}}, {"sales_name": {"$in": user_names}}, {"customer_id": {"$in": customer_ids}}, {"customer_name": {"$in": customer_names}}, {"quotation_number": {"$in": quotation_numbers}}]}),
        ("sales_targets", {"$or": [{"sales_id": {"$in": user_ids}}, {"sales_name": {"$in": user_names}}]}),
        ("tasks", {"$or": [{"assigned_user": {"$in": user_names}}, {"customer_name": {"$in": customer_names}}, {"opportunity_name": {"$in": opportunity_names}}]}),
        ("quotations", {"items.product_id": {"$in": product_ids}}),
        ("purchase_orders", {"items.product_id": {"$in": product_ids}}),
    ]
    for collection, query in reference_checks:
        if await _find_production_reference(collection, query):
            raise ValueError(f"Clear Dummy dibatalkan: masih ada data production yang mereferensikan demo pada collection {collection}.")

    deleted = {}
    for collection in CLEAR_ORDER:
        result = await db[collection].delete_many({"is_demo": True})
        deleted[collection] = int(result.deleted_count)
    return {"deleted": deleted}
