from datetime import timedelta
import uuid

from lib.db import db, pwd_context
from routers.common import now


DEMO_COUNTS = {
    "users": 10,
    "customers": 10,
    "products": 10,
    "sales_targets": 10,
    "opportunities": 10,
    "activities": 10,
    "quotations": 10,
    "purchase_orders": 10,
    "tasks": 10,
}

CREATE_ORDER = [
    "users",
    "customers",
    "products",
    "sales_targets",
    "opportunities",
    "activities",
    "quotations",
    "purchase_orders",
    "tasks",
]

CLEAR_ORDER = [
    "tasks",
    "purchase_orders",
    "quotations",
    "activities",
    "opportunities",
    "sales_targets",
    "customers",
    "products",
    "users",
]


def _id() -> str:
    return str(uuid.uuid4())


def _demo_doc(**fields):
    return {"id": _id(), "is_demo": True, "created_at": now(), **fields}


async def _demo_exists() -> bool:
    for collection in CREATE_ORDER:
        if await db[collection].find_one({"is_demo": True}, {"_id": 1}):
            return True
    return False


async def _rollback(created: dict[str, list[str]]) -> None:
    for collection in reversed(CREATE_ORDER):
        ids = created.get(collection, [])
        if ids:
            await db[collection].delete_many({"id": {"$in": ids}})


async def generate_demo_data() -> dict:
    if await _demo_exists():
        raise ValueError("Demo data sudah tersedia. Jalankan Clear Dummy terlebih dahulu.")

    created: dict[str, list[str]] = {name: [] for name in CREATE_ORDER}
    created_docs: dict[str, list[dict]] = {name: [] for name in CREATE_ORDER}

    try:
        # 1. Users: one manager + nine sales. No demo SUPER_ADMIN is created.
        manager = _demo_doc(
            user_id="USR-DEMO-001",
            name="Demo Manager",
            email="demo.manager@crm-demo.local",
            role="SALES_MANAGER",
            manager_id=None,
            phone="08120000001",
            status="Active",
            password_hash=pwd_context.hash("Password123"),
            failed_login_attempts=0,
            locked_until=None,
        )
        users = [manager]
        for index in range(2, 11):
            users.append(
                _demo_doc(
                    user_id=f"USR-DEMO-{index:03d}",
                    name=f"Demo Sales {index - 1}",
                    email=f"demo.sales{index - 1:02d}@crm-demo.local",
                    role="SALES",
                    manager_id=manager["id"],
                    phone=f"08120000{index:03d}",
                    status="Active",
                    password_hash=pwd_context.hash("Password123"),
                    failed_login_attempts=0,
                    locked_until=None,
                )
            )
        await db.users.insert_many(users)
        created["users"] = [item["id"] for item in users]
        created_docs["users"] = users
        sales_users = users[1:]

        # 2. Customers.
        customers = []
        for index in range(1, 11):
            sales = sales_users[(index - 1) % len(sales_users)]
            customers.append(
                _demo_doc(
                    customer_id=f"CUS-DEMO-{index:03d}",
                    name=f"Demo Customer {index:02d}",
                    company_name=f"PT Demo Industri {index:02d}",
                    company=f"PT Demo Industri {index:02d}",
                    industry=["Manufacturing", "Oil & Gas", "Automation", "Food & Beverage"][index % 4],
                    source="Dummy Data",
                    city="Jakarta",
                    province="DKI Jakarta",
                    phone=f"021555{index:04d}",
                    email=f"customer{index:02d}@crm-demo.local",
                    pic_name=f"PIC Demo {index:02d}",
                    pic_position="Procurement",
                    status="Active",
                    sales_id=sales["id"],
                    sales_name=sales["name"],
                    address=f"Jl. Demo Industri No. {index}, Jakarta",
                    notes="Generated by CRM Generate Dummy.",
                    updated_at=now(),
                )
            )
        await db.customers.insert_many(customers)
        created["customers"] = [item["id"] for item in customers]
        created_docs["customers"] = customers

        # 3. Products.
        products = []
        for index in range(1, 11):
            products.append(
                _demo_doc(
                    code=f"PRD-DEMO-{index:03d}",
                    name=f"Demo Product {index:02d}",
                    brand=["Axiomtek", "Watlow", "ICPDAS", "Eurotherm"][index % 4],
                    category=["Industrial PC", "Heater", "Remote I/O", "Controller"][index % 4],
                    unit="pcs",
                    default_price=float(index * 2500000),
                    supplier="Demo Supplier",
                    status="Active",
                    description="Generated by CRM Generate Dummy.",
                    updated_at=now(),
                )
            )
        await db.products.insert_many(products)
        created["products"] = [item["id"] for item in products]
        created_docs["products"] = products

        # 4. Sales targets.
        current_year = now().year
        targets = []
        for index, sales in enumerate(sales_users, start=1):
            targets.append(
                _demo_doc(
                    sales_id=sales["id"],
                    sales_name=sales["name"],
                    year=current_year,
                    target=float(300000000 + index * 25000000),
                    updated_at=now(),
                )
            )
        await db.sales_targets.insert_many(targets)
        created["sales_targets"] = [item["id"] for item in targets]
        created_docs["sales_targets"] = targets

        # 5. Opportunities.
        stages = ["Lead", "Qualification", "Proposal", "Negotiation", "Won", "Lost"]
        opportunities = []
        for index in range(1, 11):
            customer = customers[index - 1]
            stage = stages[(index - 1) % len(stages)]
            sales = sales_users[(index - 1) % len(sales_users)]
            opportunities.append(
                _demo_doc(
                    opportunity_id=f"OPP-DEMO-{index:03d}",
                    name=f"Demo Opportunity {index:02d}",
                    customer_id=customer["id"],
                    customer_name=customer["name"],
                    sales_id=sales["id"],
                    sales_name=sales["name"],
                    value=float(50000000 + index * 17500000),
                    probability={"Lead": 10, "Qualification": 25, "Proposal": 50, "Negotiation": 75, "Won": 100, "Lost": 0}[stage],
                    stage=stage,
                    target_close=(now() + timedelta(days=15 + index * 3)).date(),
                    brand=["Axiomtek", "Watlow", "ICPDAS", "Eurotherm"][index % 4],
                    product=products[(index - 1) % len(products)]["name"],
                    next_action="Follow up customer",
                    description="Generated by CRM Generate Dummy.",
                    loss_reason="Budget / competition" if stage == "Lost" else None,
                    updated_at=now(),
                )
            )
        await db.opportunities.insert_many(opportunities)
        created["opportunities"] = [item["id"] for item in opportunities]
        created_docs["opportunities"] = opportunities

        # 6. Activities.
        activity_types = ["Call", "WhatsApp", "Email", "Meeting", "Visit", "Presentation", "Follow Up"]
        activities = []
        for index in range(1, 11):
            customer = customers[index - 1]
            opportunity = opportunities[index - 1]
            sales = sales_users[(index - 1) % len(sales_users)]
            activities.append(
                _demo_doc(
                    activity_id=f"ACT-DEMO-{index:03d}",
                    subject=f"Demo Activity {index:02d}",
                    activity_type=activity_types[(index - 1) % len(activity_types)],
                    date=(now() - timedelta(days=index)).date(),
                    customer_id=customer["id"],
                    customer_name=customer["name"],
                    opportunity_id=opportunity["id"],
                    sales_id=sales["id"],
                    sales_name=sales["name"],
                    next_follow_up=(now() - timedelta(days=2)).date() if index in {3, 7} else (now() + timedelta(days=index)).date(),
                    status="Completed" if index in {1, 4, 8} else "Open",
                    description="Generated by CRM Generate Dummy.",
                    updated_at=now(),
                )
            )
        await db.activities.insert_many(activities)
        created["activities"] = [item["id"] for item in activities]
        created_docs["activities"] = activities

        # 7. Quotations. Demo numbering never touches production number_sequences.
        quotation_statuses = ["Draft", "Sent", "Negotiation", "Approved", "Rejected", "Expired", "Converted"]
        quotations = []
        for index in range(1, 11):
            customer = customers[index - 1]
            opportunity = opportunities[index - 1]
            sales = sales_users[(index - 1) % len(sales_users)]
            product = products[(index - 1) % len(products)]
            unit_price = float(product["default_price"])
            quantity = (index % 3) + 1
            subtotal = unit_price * quantity
            discount_total = subtotal * (0.05 if index % 4 == 0 else 0)
            tax_total = (subtotal - discount_total) * 0.11
            quotations.append(
                _demo_doc(
                    number=f"QT-DEMO-{index:03d}",
                    customer_id=customer["id"],
                    customer_name=customer["name"],
                    sales_id=sales["id"],
                    sales_name=sales["name"],
                    opportunity_id=opportunity["id"],
                    date=(now() - timedelta(days=index)).date(),
                    valid_until=(now() + timedelta(days=30)).date(),
                    payment_term="30 Days",
                    delivery_term="4-6 Weeks",
                    notes="Generated by CRM Generate Dummy.",
                    items=[{
                        "product_id": product["id"],
                        "description": product["name"],
                        "quantity": quantity,
                        "unit_price": unit_price,
                        "discount": discount_total,
                        "tax": tax_total,
                        "total": subtotal - discount_total + tax_total,
                    }],
                    subtotal=subtotal,
                    discount_total=discount_total,
                    tax_total=tax_total,
                    grand_total=subtotal - discount_total + tax_total,
                    status=quotation_statuses[(index - 1) % len(quotation_statuses)],
                    updated_at=now(),
                )
            )
        await db.quotations.insert_many(quotations)
        created["quotations"] = [item["id"] for item in quotations]
        created_docs["quotations"] = quotations

        # 8. Purchase orders. Links use quotation.number and product.id.
        order_statuses = ["Received", "Waiting Order", "Confirmed", "Processing", "Indent", "Ready Stock", "Delivery", "Completed", "Cancelled"]
        purchase_orders = []
        for index in range(1, 11):
            customer = customers[index - 1]
            quotation = quotations[index - 1]
            sales = sales_users[(index - 1) % len(sales_users)]
            product = products[(index - 1) % len(products)]
            quantity = (index % 3) + 1
            unit_price = float(product["default_price"])
            total = unit_price * quantity * 1.11
            purchase_orders.append(
                _demo_doc(
                    po_number=f"PO-DEMO-{index:03d}",
                    customer_id=customer["id"],
                    customer_name=customer["name"],
                    sales_id=sales["id"],
                    sales_name=sales["name"],
                    date=(now() - timedelta(days=index)).date(),
                    status=order_statuses[(index - 1) % len(order_statuses)],
                    quotation_number=quotation["number"],
                    quotation_manual=False,
                    items=[{
                        "product_id": product["id"],
                        "description": product["name"],
                        "quantity": quantity,
                        "unit_price": unit_price,
                        "discount": 0,
                        "tax": 11,
                    }],
                    total=total,
                    eta=(now() + timedelta(days=7 + index)).date(),
                    payment_term="30 Days",
                    supplier="Demo Supplier",
                    shipping_address=customer["address"],
                    document_name=f"PO-DEMO-{index:03d}.pdf",
                    updated_at=now(),
                )
            )
        await db.purchase_orders.insert_many(purchase_orders)
        created["purchase_orders"] = [item["id"] for item in purchase_orders]
        created_docs["purchase_orders"] = purchase_orders

        # 9. Tasks use the existing string-based model fields.
        tasks = []
        for index in range(1, 11):
            customer = customers[index - 1]
            opportunity = opportunities[index - 1]
            sales = sales_users[(index - 1) % len(sales_users)]
            tasks.append(
                _demo_doc(
                    title=f"Demo Task {index:02d}",
                    due_date=(now() + timedelta(days=index - 5)).date(),
                    priority=["Low", "Medium", "High"][index % 3],
                    status="Completed" if index in {2, 6, 10} else "Pending",
                    customer_name=customer["name"],
                    opportunity_name=opportunity["name"],
                    assigned_user=sales["name"],
                    updated_at=now(),
                )
            )
        await db.tasks.insert_many(tasks)
        created["tasks"] = [item["id"] for item in tasks]
        created_docs["tasks"] = tasks

        # Referential integrity checks for the generated graph.
        user_ids = {item["id"] for item in users}
        customer_ids = {item["id"] for item in customers}
        product_ids = {item["id"] for item in products}
        opportunity_ids = {item["id"] for item in opportunities}
        quotation_ids = {item["id"] for item in quotations}
        quotation_numbers = {item["number"] for item in quotations}
        assert all(item.get("manager_id") in user_ids or item.get("manager_id") is None for item in users)
        assert all(item.get("sales_id") in user_ids for item in customers)
        assert all(item.get("customer_id") in customer_ids and item.get("sales_id") in user_ids for item in opportunities)
        assert all(item.get("customer_id") in customer_ids and item.get("opportunity_id") in opportunity_ids and item.get("sales_id") in user_ids for item in activities)
        assert all(item.get("customer_id") in customer_ids and item.get("sales_id") in user_ids and item.get("opportunity_id") in opportunity_ids and all(i.get("product_id") in product_ids for i in item.get("items", [])) for item in quotations)
        assert all(item.get("customer_id") in customer_ids and item.get("sales_id") in user_ids and item.get("quotation_number") in quotation_numbers and all(i.get("product_id") in product_ids for i in item.get("items", [])) for item in purchase_orders)
        assert len(quotation_ids) == len(quotations)

        return {"counts": {name: len(created_docs[name]) for name in CREATE_ORDER}}
    except Exception:
        await _rollback(created)
        raise


async def _find_production_reference(collection: str, query: dict) -> bool:
    return await db[collection].find_one({"is_demo": {"$ne": True}, **query}, {"_id": 1}) is not None


async def clear_demo_data() -> dict:
    demo_users = await db.users.find({"is_demo": True}, {"id": 1, "user_id": 1, "name": 1}).to_list(1000)
    demo_customers = await db.customers.find({"is_demo": True}, {"id": 1, "customer_id": 1, "name": 1}).to_list(1000)
    demo_products = await db.products.find({"is_demo": True}, {"id": 1, "code": 1}).to_list(1000)
    demo_opportunities = await db.opportunities.find({"is_demo": True}, {"id": 1, "opportunity_id": 1, "name": 1}).to_list(1000)
    demo_quotations = await db.quotations.find({"is_demo": True}, {"id": 1, "number": 1}).to_list(1000)

    if not any([demo_users, demo_customers, demo_products, demo_opportunities, demo_quotations]):
        return {"deleted": {name: 0 for name in CLEAR_ORDER}}

    user_ids = [item["id"] for item in demo_users]
    user_names = [item.get("name") for item in demo_users if item.get("name")]
    customer_ids = [item["id"] for item in demo_customers]
    customer_names = [item.get("name") for item in demo_customers if item.get("name")]
    product_ids = [item["id"] for item in demo_products]
    opportunity_ids = [item["id"] for item in demo_opportunities]
    opportunity_names = [item.get("name") for item in demo_opportunities if item.get("name")]
    quotation_numbers = [item["number"] for item in demo_quotations if item.get("number")]

    # Abort if a non-demo production document references demo entities.
    reference_checks = [
        ("customers", {"$or": [{"sales_id": {"$in": user_ids}}, {"sales_name": {"$in": user_names}}]}),
        ("opportunities", {"$or": [{"sales_id": {"$in": user_ids}}, {"sales_name": {"$in": user_names}}, {"customer_id": {"$in": customer_ids}}, {"customer_name": {"$in": customer_names}}]}),
        ("activities", {"$or": [{"sales_id": {"$in": user_ids}}, {"sales_name": {"$in": user_names}}, {"customer_id": {"$in": customer_ids}}, {"customer_name": {"$in": customer_names}}, {"opportunity_id": {"$in": opportunity_ids}}]}),
        ("quotations", {"$or": [{"sales_id": {"$in": user_ids}}, {"sales_name": {"$in": user_names}}, {"customer_id": {"$in": customer_ids}}, {"customer_name": {"$in": customer_names}}, {"opportunity_id": {"$in": opportunity_ids}}]}),
        ("purchase_orders", {"$or": [{"sales_id": {"$in": user_ids}}, {"sales_name": {"$in": user_names}}, {"customer_id": {"$in": customer_ids}}, {"customer_name": {"$in": customer_names}}, {"quotation_number": {"$in": quotation_numbers}}]}),
        ("sales_targets", {"$or": [{"sales_id": {"$in": user_ids}}, {"sales_name": {"$in": user_names}}]}),
        ("tasks", {"$or": [{"assigned_user": {"$in": user_names}}, {"customer_name": {"$in": customer_names}}, {"opportunity_name": {"$in": opportunity_names}}]}),
        ("quotations", {"items.product_id": {"$in": product_ids}}),
        ("purchase_orders", {"items.product_id": {"$in": product_ids}}),
    ]
    for collection, query in reference_checks:
        if await _find_production_reference(collection, query):
            raise ValueError(f"Clear Dummy dibatalkan: masih ada data production yang mereferensikan demo pada collection {collection}.")

    deleted: dict[str, int] = {}
    for collection in CLEAR_ORDER:
        result = await db[collection].delete_many({"is_demo": True})
        deleted[collection] = int(result.deleted_count)
    return {"deleted": deleted}
