import { useQuery } from "@tanstack/react-query";
import { apiGet } from "@/lib/api";
import type { DashboardMetrics } from "@/lib/types";
import PageHeader from "@/components/PageHeader";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Activity, BarChart3, CheckCircle2, ClipboardList, FileText, PackageCheck, ShoppingCart, Users, WalletCards } from "lucide-react";

const money = (value: number) => new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(value);

export default function Home() {
  const { data, isLoading, isError, refetch } = useQuery({ queryKey: ["dashboard"], queryFn: () => apiGet<DashboardMetrics>("/dashboard"), retry: false });
  const cards = data ? [{ label: "TOTAL CUSTOMER", value: data.total_customer.toLocaleString("id-ID"), note: "Customer dalam database", icon: Users }, { label: "OPEN PIPELINE", value: money(data.open_pipeline), note: "Nilai deal berjalan", icon: BarChart3 }, { label: "WEIGHTED PIPELINE", value: money(data.weighted_pipeline), note: "Value × probability", icon: WalletCards }, { label: "WON VALUE", value: money(data.won_value), note: "Nilai opportunity won", icon: CheckCircle2 }, { label: "TOTAL QUOTATION", value: data.total_quotation.toLocaleString("id-ID"), note: "Quotation tercatat", icon: FileText }, { label: "TOTAL PO", value: data.total_po.toLocaleString("id-ID"), note: "Purchase order", icon: ShoppingCart }, { label: "PO VALUE", value: money(data.po_value), note: "Nilai order", icon: PackageCheck }, { label: "AKTIVITAS", value: data.activities.toLocaleString("id-ID"), note: "Aktivitas sales", icon: Activity }, { label: "OPEN ORDERS", value: data.open_orders.toLocaleString("id-ID"), note: "Order belum selesai", icon: ClipboardList }, { label: "COMPLETED ORDERS", value: data.completed_orders.toLocaleString("id-ID"), note: "Order selesai", icon: CheckCircle2 }, { label: "OVERDUE ORDERS", value: data.overdue_orders.toLocaleString("id-ID"), note: "ETA terlewat", icon: ClipboardList }] : [];
  return <div data-testid="dashboard-page"><PageHeader title="Dashboard" description="Ringkasan performa sales — dihitung penuh di server (aggregation)" onRefresh={() => void refetch()} />{isError && <div className="mb-6 rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800" data-testid="dashboard-error">Data dashboard belum tersedia. Silakan refresh setelah server terhubung.</div>}<div className="grid grid-cols-1 gap-4 md:grid-cols-3 lg:grid-cols-4">{cards.map(({ label, value, note, icon: Icon }) => <Card key={label} className="h-full border-slate-200 shadow-sm" data-testid={`dashboard-kpi-${label.toLowerCase().replaceAll(" ", "-")}`}><CardContent className="p-5"><div className="flex items-start justify-between"><div className="text-[11px] font-semibold tracking-wider text-slate-500">{label}</div><Icon className="size-4 text-slate-400" /></div><div className="mt-5 font-heading text-2xl font-bold tracking-tight text-slate-900">{isLoading ? "—" : value}</div><div className="mt-3 text-xs text-slate-500">{note}</div></CardContent></Card>)}</div>{data && <Card className="mt-6 border-slate-200 shadow-sm" data-testid="dashboard-pipeline-stage-card"><CardContent className="p-6"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-heading text-xl font-semibold">Pipeline per Stage</h2><p className="mt-1 text-sm text-slate-500">Nilai deal dikelompokkan di database (GROUP BY)</p></div><Badge variant="outline">Server aggregation</Badge></div><div className="space-y-5">{data.pipeline_by_stage.map(stage => <div key={stage.stage} data-testid={`pipeline-stage-${stage.stage.toLowerCase()}`}><div className="mb-2 flex justify-between text-sm"><span className="font-medium">{stage.stage} <span className="text-slate-400">({stage.count})</span></span><span className="font-mono text-xs text-slate-500">{money(stage.value)}</span></div><div className="h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-blue-600 transition-[width] duration-300" style={{ width: `${Math.max(4, Math.min(100, (stage.value / Math.max(...data.pipeline_by_stage.map(item => item.value), 1)) * 100))}%` }} /></div></div>)}</div></CardContent></Card>}</div>;
}
