import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { apiGet, apiPatch } from "@/lib/api";
import type { Paginated, PurchaseOrder } from "@/lib/types";
import PageHeader from "@/components/PageHeader";
import DataTable from "@/components/DataTable";
import { Badge } from "@/components/ui/badge";
import { selectClass } from "@/components/Field";
import { toast } from "sonner";

const stages = ["Received", "Processing", "Indent", "Ready Stock", "Delivery", "Completed"];
export default function OrderMonitoring() { const qc = useQueryClient(); const query = useQuery({ queryKey: ["order-monitoring"], queryFn: () => apiGet<Paginated<PurchaseOrder>>("/purchase-orders/monitoring?page=1&page_size=50") }); const update = useMutation({ mutationFn: ({ id, status }: { id: string; status: string }) => apiPatch<PurchaseOrder>(`/purchase-orders/${id}/status?status=${encodeURIComponent(status)}`), onSuccess: () => { qc.invalidateQueries({ queryKey: ["order-monitoring"] }); qc.invalidateQueries({ queryKey: ["dashboard"] }); toast.success("Status order diperbarui"); } }); const items = query.data?.items ?? []; const stats = [{ label: "TOTAL", value: items.length }, ...stages.map(stage => ({ label: stage.toUpperCase(), value: items.filter(i => i.status === stage).length }))]; return <div data-testid="order-monitoring-page"><PageHeader title="Order Monitoring" description="PO Diterima → Processing → Indent → Ready Stock → Delivery → Completed" onRefresh={() => void query.refetch()} onExport={() => window.open("/api/exports/purchase-orders", "_blank")} /><div className="mb-6 grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-7">{stats.map(stat => <div key={stat.label} className="rounded-lg border border-slate-200 bg-white p-4" data-testid={`order-stat-${stat.label.toLowerCase().replaceAll(" ", "-")}`}><div className="text-[10px] font-semibold tracking-wider text-slate-500">{stat.label}</div><div className="mt-2 font-mono text-2xl font-semibold">{stat.value}</div></div>)}</div><DataTable testId="order-monitoring-table" items={items} loading={query.isLoading} total={query.data?.total} columns={[{ key: "id", label: "Monitoring ID", render: i => <span className="font-mono text-[10px] text-slate-500">{i.id.slice(0, 8).toUpperCase()}</span> }, { key: "po", label: "Nomor PO", render: i => <span className="font-medium">{i.po_number}</span> }, { key: "customer", label: "Customer", render: i => i.customer_name }, { key: "product", label: "Produk", render: i => i.items[0]?.description ?? "—" }, { key: "qty", label: "Qty", render: i => `${i.items[0]?.quantity ?? 0}` }, { key: "status", label: "Status", render: i => <select className={`${selectClass} min-w-36`} value={i.status} onChange={e => update.mutate({ id: i.id, status: e.target.value })} data-testid={`order-status-${i.id}`}>{stages.map(s => <option key={s}>{s}</option>)}</select> }, { key: "supplier", label: "Supplier", render: i => i.supplier ?? "—" }, { key: "eta", label: "ETA", render: i => i.eta ?? "—" }, { key: "indicator", label: "Indikator", render: i => <Badge variant={i.status === "Completed" ? "default" : "outline"}>{i.status === "Completed" ? "Selesai" : "Berjalan"}</Badge> }, { key: "sales", label: "Sales", render: i => i.sales_name ?? "—" }]} /></div>; }