import { useQuery } from "@tanstack/react-query";
import { AlertTriangle, BarChart3, Gauge, RefreshCw, Target, TrendingUp, Trophy } from "lucide-react";
import { apiGet } from "@/lib/api";
import type { DashboardMetrics } from "@/lib/types";
import { Button } from "@/components/ui/button";

const money = (value: number) => new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(value);
const compact = (value: number) => new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", notation: "compact", maximumFractionDigits: 1 }).format(value).replace("IDR", "Rp");
const percent = (value: number) => `${Math.max(0, value).toFixed(1)}%`;

function Metric({ label, value, note, icon: Icon, tone = "blue" }: { label: string; value: string; note: string; icon: typeof Target; tone?: "blue" | "green" | "amber" | "slate" }) {
  const tones = { blue: "bg-blue-50 text-blue-600", green: "bg-emerald-50 text-emerald-600", amber: "bg-amber-50 text-amber-600", slate: "bg-slate-100 text-slate-600" };
  return <div className="rounded-lg border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between gap-2"><span className="text-xs font-bold tracking-[.12em] text-slate-500">{label}</span><div className={`rounded-lg p-1.5 ${tones[tone]}`}><Icon className="size-4" /></div></div><div className="mt-2 font-heading text-2xl font-bold text-slate-950">{value}</div><div className="mt-1 text-sm text-slate-500">{note}</div></div>;
}
function Empty({ text }: { text: string }) { return <div className="p-4 text-sm text-slate-500">{text}</div>; }
function Section({ title, subtitle, icon: Icon, children, className = "" }: { title: string; subtitle?: string; icon?: typeof BarChart3; children: React.ReactNode; className?: string }) { return <section className={`rounded-lg border border-slate-200 bg-white shadow-sm ${className}`}><div className="border-b border-slate-100 px-5 py-3.5"><div className="flex items-center gap-2">{Icon && <Icon className="size-5 text-blue-600" />}<h2 className="font-heading text-xl font-bold text-slate-900">{title}</h2></div>{subtitle && <p className="mt-0.5 text-sm text-slate-500">{subtitle}</p>}</div>{children}</section>; }

export default function SalesIntelligence() {
  const query = useQuery({ queryKey: ["sales-intelligence"], queryFn: () => apiGet<DashboardMetrics>("/dashboard"), staleTime: 30_000, refetchInterval: 300_000, retry: 1 });
  const data = query.data;
  if (query.isLoading) return <div className="space-y-4"><div className="h-24 animate-pulse rounded-lg bg-slate-200" /><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5">{Array.from({ length: 5 }).map((_, i) => <div key={i} className="h-28 rounded-lg border border-slate-200 bg-white animate-pulse" />)}</div></div>;
  if (query.isError || !data) return <div className="rounded-lg border border-red-200 bg-red-50 p-5 text-sm text-red-800"><div className="font-semibold">Sales Intelligence gagal mengambil data Dashboard.</div><Button variant="outline" size="sm" className="mt-3" onClick={() => query.refetch()}><RefreshCw className="mr-2 size-4" />Coba lagi</Button></div>;

  const target = Number(data.sales_target) || 0;
  const won = Number(data.won_value) || 0;
  const open = Number(data.open_pipeline) || 0;
  const weighted = Number(data.weighted_pipeline) || 0;
  const forecast = won + weighted;
  const remainingTarget = Math.max(0, target - won);
  const coverage = remainingTarget > 0 ? open / remainingTarget : 0;
  const coverageStatus = remainingTarget <= 0 ? "Target achieved" : coverage >= 1 ? "Covered" : "Under-covered";
  const coverageNote = remainingTarget <= 0 ? "No remaining target" : coverage >= 1 ? "Open pipeline covers remaining target" : "Open pipeline below remaining target";
  const achievement = target > 0 ? (won / target) * 100 : Number(data.target_achievement) || 0;
  const winRate = Number(data.win_rate) || 0;
  const forecastGap = Math.max(0, target - forecast);
  const forecastSurplus = Math.max(0, forecast - target);
  const forecastOnTarget = target > 0 && Math.abs(forecast - target) < 0.005;
  const noForecastTarget = target <= 0;
  const forecastAchievement = target > 0 ? (forecast / target) * 100 : 0;
  const forecastNote = noForecastTarget ? "No sales target configured" : `${percent(forecastAchievement)} dari target`;
  const riskCount = data.deal_risks.length;
  const maxStage = Math.max(...data.pipeline_by_stage.map(row => Number(row.value) || 0), 1);
  const maxSales = Math.max(...data.pipeline_by_salesperson.map(row => Number(row.value) || 0), 1);
  const maxMonthly = Math.max(...data.monthly_sales_performance.map(row => Math.max(Number(row.actual) || 0, Number(row.target) || 0)), 1);
  const openOpps = data.pipeline_by_stage.reduce((sum, row) => {
    const stage = String(row.name || "").trim().toLowerCase();
    const isClosed = stage === "won" || stage === "lost" || stage.includes("closed won") || stage.includes("closed lost");
    return isClosed ? sum : sum + Number(row.count || 0);
  }, 0);

  return <div className="space-y-4" data-testid="sales-intelligence-page">
    <div className="rounded-xl bg-gradient-to-r from-[#071126] via-[#101e42] to-[#172a58] px-6 py-5 text-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="text-xs font-bold uppercase tracking-[.16em] text-blue-300">SALES MANAGEMENT INTELLIGENCE</div><h1 className="mt-1 font-heading text-3xl font-bold tracking-tight">Sales Intelligence</h1><p className="mt-1 text-sm text-slate-300">Target, forecast, pipeline coverage, win rate, dan risiko opportunity.</p><div className="mt-2 flex flex-wrap items-center gap-2 text-xs text-slate-300"><span className="rounded-full bg-white/10 px-2.5 py-1">Auto-refresh 5 menit</span>{query.isFetching ? <span className="flex items-center gap-1 rounded-full bg-white/10 px-2.5 py-1"><RefreshCw className="size-3 animate-spin" />Memperbarui...</span> : data.generated_at ? <span className="rounded-full bg-white/10 px-2.5 py-1">Data: {new Date(data.generated_at).toLocaleString("id-ID")}</span> : null}</div></div><Button variant="secondary" size="sm" onClick={() => query.refetch()} disabled={query.isFetching} className="shrink-0 bg-white/10 text-white hover:bg-white/20"><RefreshCw className={`mr-2 size-4 ${query.isFetching ? "animate-spin" : ""}`} />Refresh</Button></div></div>

    <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5"><Metric label="TARGET" value={compact(target)} note="Target scope user" icon={Target} /><Metric label="ACHIEVEMENT" value={percent(achievement)} note={`${money(won)} won`} icon={Trophy} tone="green" /><Metric label="FORECAST" value={compact(forecast)} note={forecastNote} icon={TrendingUp} /><Metric label="PIPELINE COVERAGE" value={remainingTarget <= 0 ? "—" : `${coverage.toFixed(1)}x`} note={`${coverageStatus} · ${compact(remainingTarget)} remaining`} icon={Gauge} tone="amber" /><Metric label="WIN RATE" value={percent(winRate)} note={`${data.total_opportunities} opportunities`} icon={Trophy} tone="slate" /></div>
    <div className="text-sm text-slate-500">Pipeline coverage: {coverageNote}.</div>

    <div className="grid gap-3 md:grid-cols-3"><div className="rounded-lg border border-slate-200 bg-white px-4 py-3 shadow-sm"><div className="text-xs font-bold tracking-[.12em] text-slate-500">{noForecastTarget ? "FORECAST STATUS" : forecastOnTarget ? "FORECAST STATUS" : forecastSurplus > 0 ? "FORECAST SURPLUS" : "FORECAST GAP"}</div><div className="mt-1 text-xl font-bold text-slate-950">{compact(noForecastTarget || forecastOnTarget ? 0 : forecastSurplus > 0 ? forecastSurplus : forecastGap)}</div><div className="text-sm text-slate-500">{noForecastTarget ? "No sales target configured" : forecastOnTarget ? "Forecast tepat mencapai target" : forecastSurplus > 0 ? "Forecast berada di atas target" : "Remaining setelah weighted pipeline"}</div></div><div className="rounded-lg border border-slate-200 bg-white px-4 py-3 shadow-sm"><div className="text-xs font-bold tracking-[.12em] text-slate-500">OPEN OPPORTUNITIES</div><div className="mt-1 text-xl font-bold text-slate-950">{openOpps}</div><div className="text-sm text-slate-500">Current sales scope, excluding Won/Lost</div></div><div className="rounded-lg border border-slate-200 bg-white px-4 py-3 shadow-sm"><div className="text-xs font-bold tracking-[.12em] text-slate-500">RISK WATCHLIST</div><div className="mt-1 text-xl font-bold text-slate-950">{riskCount}</div><div className="text-sm text-slate-500">Opportunities flagged</div></div></div>

    <Section title="Monthly Sales Performance" subtitle="Actual PO value dibandingkan target bulanan pada scope user" icon={BarChart3}><div className="grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-4">{data.monthly_sales_performance.map((row) => { const actual = Number(row.actual) || 0; const monthlyTarget = Number(row.target) || 0; const achievementValue = monthlyTarget > 0 ? (actual / monthlyTarget) * 100 : 0; return <div key={row.month} className="rounded-lg border border-slate-100 bg-slate-50 p-3"><div className="flex items-center justify-between gap-2"><span className="text-base font-bold text-slate-900">{row.label}</span><span className="text-sm font-bold text-slate-600">{monthlyTarget > 0 ? percent(achievementValue) : "—"}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-blue-600" style={{ width: `${Math.min(100, (actual / maxMonthly) * 100)}%` }} /></div><div className="mt-2 flex items-center justify-between gap-2 text-sm"><span className="font-semibold text-slate-700">Won/PO {compact(actual)}</span><span className="text-slate-500">Target {compact(monthlyTarget)}</span></div></div>; })}</div></Section>

    <div className="grid gap-4 xl:grid-cols-[1.2fr_1fr]"><Section title="Pipeline by Stage" subtitle="Value and opportunity count by current stage" icon={BarChart3}><div className="space-y-3 p-4">{data.pipeline_by_stage.length === 0 ? <Empty text="Belum ada pipeline." /> : data.pipeline_by_stage.map((row) => <div key={row.name}><div className="mb-1 flex items-center justify-between gap-3 text-base"><span className="font-semibold text-slate-800">{row.name}</span><span className="font-bold text-slate-900">{compact(Number(row.value) || 0)} <span className="font-medium text-slate-500">· {row.count}</span></span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{ width: `${Math.min(100, ((Number(row.value) || 0) / maxStage) * 100)}%` }} /></div></div>)}</div></Section><Section title="Sales Performance" subtitle="Open pipeline per salesperson dalam scope Anda"><div className="space-y-3 p-4">{data.pipeline_by_salesperson.length === 0 ? <Empty text="Belum ada open pipeline." /> : data.pipeline_by_salesperson.map((row) => <div key={row.name}><div className="mb-1 flex items-center justify-between gap-3"><div className="min-w-0"><div className="truncate text-base font-bold text-slate-900">{row.name}</div><div className="text-sm text-slate-500">{row.count} open opportunity</div></div><div className="text-right text-base font-bold text-slate-900">{compact(row.value)}</div></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-slate-800" style={{ width: `${Math.min(100, ((Number(row.value) || 0) / maxSales) * 100)}%` }} /></div></div>)}</div></Section></div>

    <div className="grid gap-4 xl:grid-cols-[1.25fr_1fr]"><Section title="Management Forecast" subtitle="Forecast untuk review mingguan sales management"><div className="grid grid-cols-3 gap-3 p-4"><div className="rounded-lg bg-slate-50 p-3"><div className="text-sm font-semibold text-slate-500">Won</div><div className="mt-1 text-xl font-bold">{compact(won)}</div></div><div className="rounded-lg bg-slate-50 p-3"><div className="text-sm font-semibold text-slate-500">Weighted Pipeline</div><div className="mt-1 text-xl font-bold">{compact(weighted)}</div></div><div className="rounded-lg bg-blue-50 p-3"><div className="text-sm font-semibold text-blue-700">Forecast</div><div className="mt-1 text-xl font-bold text-blue-950">{compact(forecast)}</div></div></div></Section><Section title="Recent Activities" subtitle="Latest sales execution signals"><div className="divide-y divide-slate-100">{data.recent_activities.length === 0 ? <Empty text="Belum ada aktivitas." /> : data.recent_activities.slice(0, 6).map((item) => <div key={item.id} className="px-5 py-2.5"><div className="truncate text-base font-semibold text-slate-900">{item.subject}</div><div className="mt-0.5 truncate text-sm text-slate-500">{item.customer_name || "No customer"} · {item.sales_name || "Unassigned"}</div></div>)}</div></Section></div>

    <Section title="Opportunity Risks" subtitle="Prioritas follow-up berdasarkan risk engine CRM"><div className="divide-y divide-slate-100">{data.deal_risks.length === 0 ? <Empty text="Tidak ada opportunity berisiko." /> : data.deal_risks.slice(0, 8).map((risk) => <div key={risk.id} className="flex items-start gap-3 px-5 py-3"><AlertTriangle className="mt-1 size-5 shrink-0 text-amber-500" /><div className="min-w-0 flex-1"><div className="truncate text-base font-bold text-slate-900">{risk.name}</div><div className="mt-0.5 text-sm text-slate-500">{risk.customer_name} · {risk.sales_name || "Unassigned"} · {risk.stage}</div><div className="mt-0.5 text-sm font-semibold text-amber-700">{risk.reason}</div></div><div className="whitespace-nowrap text-sm font-bold text-slate-700">{compact(risk.value)}</div></div>)}</div></Section>

    <div className="text-right text-xs text-slate-400">Data generated: {data.generated_at ? new Date(data.generated_at).toLocaleString("id-ID") : "-"}</div>
  </div>;
}
